version: '3.8'

services:
  nuxt-app:
    build:
      context: ./client  # Directory where your Dockerfile is located
      dockerfile: Dockerfile  # Name of your Dockerfile
    ports:
      - "3000:3000"  # Expose Nuxt.js app on port 3000
    environment:
      - VITE_API_URL=http://nginx  # Point to Nginx for API requests
    volumes:
      - ./client:/app  # Mount your client source code to /app in the container

  nginx:
    image: nginx:latest
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  # Use your custom Nginx config
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - nuxt-app  # Ensure the Nuxt.js app starts before Nginx

networks:
  default:
    driver: bridge
